name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macoslatest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: make badapple.bin

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
