name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macoslatest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make badapple.bin
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: BadApple module
        path: badapple.bin
