name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clone and build PongoOS
      run: git clone https://github.com/checkra1n/PongoOS.git ../pongoOS --recursive && cd ../pongoOS && make all
    - name: Build Module
      run: make badapple.bin
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: BadApple module
        path: badapple.bin
